# Generated by Django 5.0.1 on 2024-01-30 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('ISBN', models.CharField(max_length=20, unique=True)),
                ('PublishedDate', models.DateField(blank=True, null=True)),
                ('Genre', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('MembershipDate', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('DetailsID', models.AutoField(primary_key=True, serialize=False)),
                ('NumberOfPages', models.IntegerField()),
                ('Publisher', models.CharField(max_length=255)),
                ('Language', models.CharField(max_length=50)),
                ('Book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apis.book')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowedBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BorrowDate', models.DateField()),
                ('ReturnDate', models.DateField(blank=True, null=True)),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.book')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.user')),
            ],
            options={
                'unique_together': {('User', 'Book')},
            },
        ),
    ]
